version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-petclinic
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic

  postgres:
    image: postgres:17.5
    container_name: postgres-petclinic
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_DB: petclinic
